import { Metadata } from 'next';
import React from 'react';
import './styles/global.scss';

export const metadata: Metadata = {
  title: 'Start',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
    },
  },
  authors: [{
    name: 'hyun',
  }],
  publisher: 'Donghyun Kim',
  icons: {
    icon: '/icon.svg',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr">
      <body>{children}</body>
    </html>
  );
}
